
-- Project Euler

{-
	1. Multiples of 3 and 5

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.
-}

euler1 = sum $ [ i | i <- [3..999], rem i 3 == 0 || rem i 5 == 0 ]


{-
2. Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
-}

euler2 = seq 0 1
 where seq a b
        | b > 4000000 = 0
        | odd a = seq b (a+b)
        | allways = a + seq b (a+b)
        where allways = True



-- MAIN --

output = "Solved Eulers: " ++ items eulers
 where items (x:xs)
        | null xs = show x ++ " "
        | True = show x ++ " " ++ items xs

eulers = [1,2]

main = do putStrLn $ output

