#!/bin/bash
#Pull latest tweets

STX="[NAME]|[(l)ist|(f)low]  [(r)ead|(a)dd|(g)rab]"
twi="https://mobile.twitter.com/"
DIR="$(find -name Twit)"; clear
N=2	#number of tweets/tweeter in flow

while true; do
len=$(bc <<< $(wc -l $DIR | awk '{print $1}')-30)
printf "  Twitter: "
read n f
if [ $n ]; then echo; clear
case $n in l) tail "$DIR" -n "$len" ;;
	f) twat=($(tail "$DIR" -n $(bc <<< $len-1)))
	for i in "${twat[@]}"; do
	printf "\n\n-	-	$i	-	-\n"
	w3m -dump "$twi"$i | grep -im $N Reply -B 4; done | less ;;
	esac
case $f in a) echo "$n" >> "$DIR" ;;
	r) w3m -dump $twi$n | grep Reply -B 5 | less ;;
	g) twif=$twi$(tail "$DIR" -n $len | grep -im 1 $n)
	w3m -dump $twif | grep Reply -B 5 | less ;;
	esac
else
	printf "\n $STX\n\n"
fi
done
exit

~List~
realDonaldTrump
neiltyson
Peppe_Larsson
PSpringare
katjanouch
alicemedce
hanifbali
Ivarpi
RubinReport
