#!/bin/bash

function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }

function decimal() {
  n=` echo "$1" | sed 's/[, ]//g' `
  p=${2:-2}
  (( ${#n} < 2 )) && d=0 || d=${n:1:$p}
  n=${n:0:1}.$d
  echo $n 
}

function sci_num() {
  n=` echo "$1" | sed 's/[, ]//g' `
  p=${2:-2} #` [[ -z $2  ]] && echo 2 || echo $2 `
  s=${#n}
  m=$(( $s-1 ))
  d=` (( $m-2 < 1 )) && echo 0 || echo $(( $m-$p ))`
  n=$(( $n / 10**$d ))
  
  n=`decimal $n $p`

  echo $n'e'$m

}

function human_time() {
  [[ -z $1 ]] && echo "Takes seconds" && return
  t=$1
  s=1
  m=$((60*$s))
  h=$((60*$m))
  d=$((24*$h))

  result=''

  if (( $t > $d )); then
    r=$(( $t / $d ))
    result=$result$r"d"
    t=$(( $t - $r*$d ))
  fi
  if (( $t > $h )); then
    r=$(( $t / $h ))
    result=$result$r"h"
    t=$(( $t - $r*$h ))
  fi
  if (( $t > $m )); then
    r=$(( $t / $m ))
    result=$result$r"m"
    t=$(( $t - $r*$m ))
  fi

  result=$result$t"s"
  echo $result

}

