#!/bin/bash

player=mpv --quiet
#player=omxplayer -o hdmi -b

if [ $2 ]; then if [ $1 == "f" ]; then
youtube-dl -F $2
printf "Format: "
read U
sudo $player $(youtube-dl -gf $U $2)

else
sudo $player $(youtube-dl -gf $1 $2)
fi

else
printf "\n Syntax: bash Yurl [format]|f [url]\n\n"
fi
