#!/bin/bash
#Stream video; based on format

player="mpv --quiet"
#player="sudo omxplayer -o hdmi -b"

if [ $2 ]; then if [ $1 == "f" ]; then
youtube-dl -F $2
printf "Format: "
read U
$player $(youtube-dl -gf $U $2)
else
$player $(youtube-dl -gf $1 $2)
fi

else
printf "\n Syntax: bash Yurl [format]|f [url]\n\n"
fi
