alias Twitch='/home/mikael/./.twitch.sh'
alias Up=/home/mikael/SCRIPT/./up
alias WebSound=/home/mikael/SCRIPT/WebSound/./webSound.sh
alias lS='ls -Ss'
alias Fake=~/SCRIPT/FakeNews/./fakeNews.sh

# $Find Look 'Exclude1|Exclude2|Excl..'
alias Find='function _seek(){ if [ ! $2 ]; then echo Searched $1 && sudo find -iname *$1*; else echo Searched $1, excluded $2 && sudo find -iname *$1* | egrep -iv $2; fi };_seek'

