#!/bin/bash

TOP="https://thepiratebay.org/top/200"
URL="https://thepiratebay.org/search/"
END="/0/99/0"

V="$(w3m -dump ip-show.com | grep "Country" | grep -i Sweden)"
if [ $V ]; then printf "Ye are not welcome here.. "; break; fi

while true; do clear
	printf "\n\033[2;35m P  I  R  A  T  E\033[2;0m\n\n"
	printf "You whom sail from $(w3m -dump whatismyipaddress.com/ | grep Country | awk '{print $2}' 2>/dev/null)..\n"
	read -p ' What fortune do you seek?
 : ' s

	if [ ! "$s" ]; then
		echo 'How about these..'
		sleep 2
		w3m -dump -o display_link_number -cols 150 $(
		echo "$TOP") |
		grep Magnet -B 1 2>/dev/null | cut -d"[" -f3- 2>/dev/null | less

		read -p "Trade a poor soul a Magnet?
 : " m
		if [ ! "$m" ]; then echo "Cold feet ay.."; break; fi

		M="$(
		w3m -dump -o display_link_number $(
		echo "$TOP") |
		grep Reference -A 200 | grep "\[$m\]" |
		awk '{print $2}') 2>/dev/null"
		rtorrent "$M"; break

	else
		for i in $s; do l+=("$i%20"); done

		w3m -dump -o display_link_number -cols 150 $(
		echo "$URL${l[@]}$END" |
		cut -d" " --output-delimiter="" -f1-) |
		grep Magnet -B 1 2>/dev/null | cut -d"[" -f3- 2>/dev/null | less

		read -p "Trade a poor soul a Magnet?
 : " m
		if [ ! "$m" ]; then echo "Cold feet ay.."; break; fi

		M="$(
		w3m -dump -o display_link_number $(
		echo "$URL${l[@]}$END" |
		cut -d" " --output-delimiter="" -f1-) |
		grep Reference -A 200 | grep "\[$m\]" |
		awk '{print $2}') 2>/dev/null "
		rtorrent "$M"; break
	fi
done


