#!/bin/bash


# Example #

#Color :: Normal  Bright  Dark

#Grey
normalGrey='\033[30m' ; brightGrey='\033[1;30m' ; darkGrey='\033[2;30m'

formatInit='\033['   # Each color start with this escape character,  color code
formatEnd=$c'0m'    # This string  '\033[0m'  resets any formating, end Formating

colors=('grey' 'red' 'green' 'orange' 'blue' 'purple' 'teal')

echo
tput smul  # Underline
printf " ____________________\r "
echo -e "Normal\t \033[1mBright\t \033[2mDark"
tput rmul  # end Underline
for (( c=0; c<${#colors[@]}; c++ )) {
  for ((f=0; f<3; f++)) {
    printf " $formatInit"$f";3"$c"m"${colors[$c]}"\t" #"$formatEnd"
  }
  echo  # New line
}

# printf "\033[1;30m grey \033[0m \t\033[30m grey \033[0m \t\033[2;30m grey \033[0m\n"
# printf "\033[1;31m red \033[0m \t\033[31m red \033[0m \t\033[2;31m red \033[0m\n"
# printf "\033[1;32m green\033[0m\t\033[32m green\033[0m\t\033[2;32m green \033[0m\n"
# printf "\033[1;33m orange\033[0m\t\033[33m orange\033[0m\t\033[2;33m orange \033[0m\n"
# printf "\033[1;34m blue \033[0m \t\033[34m blue \033[0m \t\033[2;34m blue \033[0m\n"
# printf "\033[1;35m purple\033[0m\t\033[35m purple\033[0m\t\033[2;35m purple \033[0m\n"
# printf "\033[1;36m teal \033[0m \t\033[36m teal \033[0m \t\033[2;36m teal \033[0m\n"

 printf "\033[1;36;40m Label \033[0m\t\033[33;40m Orange on black label \033[0m\n"

echo
