#!/bin/bash


page="`w3m -dump -o display_link_number=1 https://kvartal.se/inlasta-texter/`"

c=1
declare -A slices

bread="`echo "$page" | grep 'INLÄST AV' -A1 | egrep -v 'INLÄST AV|--' | sed 's/ /_/g'`"

echo
for slice in $bread; do
  slices[$c]="`echo "$slice" | sed 's/_/ /g'`"
  printf "$c: "; echo "${slices[$c]}"
  c=$(($c+1))
done
echo

printf "        n\r"
read -rep "Listen: " U
[[ -z "$U" ]] && exit

nr="`echo "$page" | grep "${slices[$U]}" -A 15 | grep 'Ladda ner' | cut -d']' -f1 | cut -d'[' -f2`"

ref="`echo "$page" | grep 'References:' -A 200 | grep "\[$nr\]" | awk -F'] ' '{print $2}'`"

echo
mpv "$ref"

