#!/bin/bash

dir=~/.notes/

[[ "$1" ]] && mv "$@" $dir && exit

while true; do
  clear; echo -e "\033[33m N o t e s\033[0m"

  declare -A file
  c=1
  printf "\n %2d: %s\n" "0" "New note"
  
  for i in `ls $dir`; do
    printf " %2d: %s\n" "$c" "$i"
    file[$c]="$i"
    c=$((c+1))
  done
  echo

  printf ' Select: n\b' && read -e I

  [[ -z "$I" ]] && clear && exit
  [[ "$I" != "0" ]] && [[ -z "${file[$I]}" ]] && 
    printf "\n\033[33;40m Valid selections are number 0-$((c-1)), or [empty] to exit \033[0m" && 
    read -e && continue

  if [[ "$I" == "0" ]]; then
    cd "$dir"
    nano -mSixT2
    cd -
  else
    nano -mSixT2 "$dir${file[$I]}"
  fi

done
