#!/bin/bash

R="\033[31m"
G="\033[32m"
O="\033[33m"
B="\033[34m"
P="\033[35m"
T="\033[36m"
L="\033[1m"
D="\033[2m"
E="\033[0m"

head="S u m m a r y"

address='192.168.43.200'  # Raspberry Pi

clear; printf "\n$D$P $head " #- $E$D$T`date`$E "
while true; do

  date=`date +'%a %H:%M %d-%b-%y'`
  #date=$date" $(( (`date +%j`*100 ) / 365 ))%"
  show="\n$D$P $head$E $D-$E $D$T$date$E $D-$E" 

  online=`ping google.com -c1 | grep '%' | cut -d',' -f2 | cut -d" " -f2`
  if (( $online == 1 )); then col=$T; else col=$D$R; fi
  show=$show"$col online $E\n"
  
  disk_space0=`df -h | head -n1 | awk '{print $1,$2,$3,$4,$5}' | sed 's/ /.../g'`
  disk_space1=`df -h | head -n2 | tail -n1 | awk '{print $1,$2,$3,$4,$5}' | sed 's/ /..../g'`
  show=$show"\n $D$B$disk_space0$E\n"
  show=$show" $D $disk_space1$E\n"
  
  online=`ping $address -c1 | grep '%' | cut -d',' -f2 | cut -d" " -f2`
  if (( $online == "1" )); then col=$T; else col=$D$R; fi
  show=$show"\n$D$B RaspberryPi: $E$col$address\n $E"

  clear
  echo -e `printf '%s\n' "$show"`

  sleep 5
done

