#!/bin/bash

W="\033[30m"
R="\033[31m"
G="\033[32m"
O="\033[33m"
B="\033[34m"
P="\033[35m"
T="\033[36m"
L="\033[1m"
D="\033[2m"
E="\033[0m"

head="L I N U X"
internet='online'
address='192.168.43.200'  # Raspberry Pi

S=10
N=1
m=0

#tput civis

#clear; printf "\n$D$P $head -$E$D press [Enter] to exit$E " ; sleep 2

function run() {
c=0
#country=''

while true; do
  
  date=`date +'%a %H:%M %d-%b-%y'`
  #date=$date" $(( (`date +%j`*100 ) / 365 ))%"
  show="\n$D$P $head$E $D-$E $D$T$date$E $D-$E" 

  online=`ping google.com -c1 -W2 2>&1 | grep '%' | cut -d',' -f2 | cut -d" " -f2`
  online=${online:-0}
  if (( $online == 1 )); then state=$L$T△; else state=$L$O▽; fi
  
  (( $online )) && (( $c % 5 )) &&
  country=" - `timeout 2s w3m -dump https://whatismyipaddress.com/ | grep City: | awk -F': ' '{print $2}'`"
  
  (( $N < $S )) && N=$(( $N+1 ))
  m=$(( $m + ((10*$S+9*($m/90))*$online-$m) / ($N) ))

  part=''
  for ((l=0;l<${#internet};l++)); do
    (( 16*($l+1) < $m )) && col=$T || col=$D$R
    part=$part$col${internet:$l:1}$E
  done
  perc=`printf "%*d%%" 3 $m`
  
  show=$show" $part$state$E$D$country$E\n"
  
  disk_space0=`df -h | head -n1 | awk '{print $1,$2,$3,$4,$5}' | sed 's/ /.../g'`
  disk_space1=`df -h | head -n2 | tail -n1 | awk '{print $1,$2,$3,$4,$5}' | sed 's/ /..../g'`
  show=$show"\n $D$B$disk_space0$E\n"
  show=$show" $D $disk_space1$E\n"
  
  online=`ping $address -c1 -W1 2>&1 | grep '%' | cut -d',' -f2 | cut -d" " -f2`
  online=${online:-0}
  if (( $online == "1" )); then col=$T; else col=$D$R; fi
  show=$show"\n$D$B RaspberryPi: $E$col$address\n $E"

  #clear
  #echo -e `printf '%s' "$show"`
  
  printf '%s' "$show" > ~/.summary_tmp

  sleep 3
  #fin=1
  #sleep 3 & (read -t 5 && wait) || fin=0
  #(( $fin )) && break
  
  (( $c == 100 )) && c=0 || c=$(($c+1))

done
}

touch ~/.summary_tmp
tput civis

run &
watch -t --color ' echo `cat ~/.summary_tmp` '

rm ~/.summary_tmp
tput cnorm


