#!/bin/bash

folder=~/Downloads/
queue=.torr

function addQueue() {
  echo "Adding to queue"
 
  name="`printf '%s' "$1" | awk -F'dn=' '{print $2}' | cut -d'%' -f1`"
  id="`printf '%s' "$1" | awk -F'btih:' '{print $2}' | cut -d'&' -f1`"

  link="$1"

  (( `grep $id $folder$queue | wc -l` )) && echo Already in queue && getQueue

  echo "$name;$id;$link" >> $folder$queue
  getQueue
}

function getQueue() {

  echo "Checking queue"
  
  active=`ps -a | grep "rtorrent" | wc -l`
  (( $active )) && echo "Already active" && exit
  
  cd $folder
  #clearQueue
  (( `cat $folder$queue | wc -l` )) &&
    rtorrent `cat $folder$queue | awk -F';' '{print $3}'`
  clearQueue
}

function clearQueue() {
  
  touch $folder"qtmp"
  for each in `cat $folder$queue`; do
    #echo "each $each"
    hasFolder=`ls $folder | grep $(echo $each | cut -d';' -f1) | wc -l`
    #echo "hasFolder: $hasFolder"
    hasMeta=`ls $folder | grep $(echo $each | cut -d';' -f2) | wc -l`
    #echo "hasMeta: $hasMeta"
    (( $hasFolder )) && (( $hasMeta )) && grep "$each" $folder$queue >> $folder"qtmp"
  done
  mv $folder"qtmp" $folder$queue
}

[[ -z $1 ]] && getQueue && exit

[[ $1 == 'h' ]] && 
  echo ' Enter url (and) quality. l,h,m::low,high,max. Attempts 480p by default' && exit
  
[[ $1 ]] && addQueue $@



exit
'
  Watch '' -> Info ; check ytdl activity ; .if !ytdl then. get queue ; exit
  Watch url -> add to queue ; check ytdl activity ; if !ytdl then. get queue ; exit
'

