#!/bin/bash

E="\033[0m"; D="\033[2m"; B="\033[1m"
r="\033[1;31m"; g="\033[1;32m"; b="\033[1;34m"; y="\033[1;33m"
space="  "; dash=" " fdash=""

# sudo -k # Reset sudo timestamp

printf "$b - Full Update - $E$D"

# Prompt for cridentials
sudo -k  # Reset sudo timestamp
sudo -v  # Update sudo timestamp

# Main Switch	(a)rch (u)buntu (r)aspberryPi (o)therStuff
active=( 1 1 0 1 1 1 )
#        u u u u u o

tasks=(
	"Update"
  "Upgrade"
  "DistroUpgrade"
  "autoRemove"
  "autoClean"
  "youtube-dl"
)
actions=(
	"sudo apt-get update -qq"
	"sudo apt-get upgrade -yqq > /dev/null"
	"sudo apt-get dist-upgrade -qq > /dev/null"
	"sudo apt-get autoremove -qq"
	"sudo apt-get autoclean -qq"
	"sudo curl -s -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl; sudo chmod a+rx /usr/local/bin/youtube-dl"
)
range=${#tasks[@]}

# Initiate
tput civis
printf "$E"
for (( i=0; i<$range; i++)); do
  if (( ${active[$i]} )); then
    printf "$space$r${tasks[$i]}"
  fi
done; printf "\r"

# Progress
for (( i=0; i<$range; i++ )); do
  if (( ${active[$i]} )); then
    printf "$space$y${tasks[$i]}"
    eval "${actions[a]}"
    task_string="$space${tasks[$i]}"
    string_length=${#task_string}
    for ((l=0; l<$string_length; l++)); do
      printf "\b"
      dash="$dash-"
    done
    printf "$space$g${tasks[$i]}"
  fi
done; printf "\n$E$D$dash \n$E"

tput cnorm
