#!/bin/bash

PWD=`pwd`

if [ ! $1 ]; then

	echo "Add path to folder containing git-folders"

else

	cd $1
	for i in `ls -l | grep 4096 | awk '{print $9}'`; do
		printf "\033[1;31m$i:\033[0m "
		cd $i; git pull; cd ..
	done
	cd $PWD

fi
