#!/bin/bash

sudo -k # Reset sudo timestamp

# Styling
e="\033[0m"; d="\033[2m"; D="\033[1m"
r="\033[1;31m"; g="\033[1;32m"; b="\033[1;34m"; y="\033[1;33m"
space="  "; dash="---------"; fdash=""; back="\b\b\b\b\b\b\b"

printf "$b - Full Update - $e$d"

# Main Switch	(a)rch (u)buntu (r)aspberryPi (o)therStuff
active=( 1 1 1 1 1 1 )
#        u u u u u o

tasks=(  # each 7 characters
	"Update " "Upgrade" "Distro " "aRemove" "aClean " " yt-dl "
)
actions=(

	"sudo apt-get update -qq"
	"sudo apt-get upgrade -yqq > /dev/null"
	"sudo apt-get dist-upgrade -qq > /dev/null"
	"sudo apt-get autoremove -qq"
	"sudo apt-get autoclean -qq"
	"sudo curl -s -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl; sudo chmod a+rx /usr/local/bin/youtube-dl"
)
range=${#tasks[@]}

sudo -v  # Update sudo timestamp

# Initial
for (( i=0; i<$range; i++ )); do
	if (( ${active[$i]} )); then
		printf "$e$space$r${tasks[$i]}"
		fdash=$fdash$dash
	fi
done; printf "\r$e"

# Progress
for (( i=0; i<$range; i++ )); do
	if (( ${active[$i]} )); then
		printf "$space$y${tasks[$i]}$e"
		eval "${actions[$i]}"
		printf "$back$g${tasks[$i]}"
	fi
done

end="\n$e$b $fdash$e\n"
printf "$end"

#read -p " Press Enter to exit"
